version: "3"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
      - ./templates/nginx.conf:/etc/nginx/nginx.conf
      - ./templates/default.conf:/etc/nginx/conf.d/default.conf
      - ./templates/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80/tcp"
      - "443:443"
#      - "3000:3000"
#      - "8009:8009"
#    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
#    environment:
#      - NGINX_HOST=127.0.0.1
#      - NGINX_PORT=80
#      - TZ=Asia/Seoul

