version: "3"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    restart: always
    ports:
      - 7020:8080
      - 50000:50000
    expose:
      - 8080
      - 50000
    volumes:
        - ./jenkins_home:/var/jenkins_home
    #      - ./home/wonseok/Documents/devWorkSpace/github/record/jenkins_home:/var/jenkins_home
    #      - /var/run/docker.sock:/var/run/docker.sock
    #      - C:\Program Files (x86)\jdk-11\lib\security\jenkins_home:/var/jenkins_home
#    networks:
#      - default
#      - jenkins-net
    user: root
    environment:
      TZ: "Asia/Seoul"
    privileged: true
    #https://hub.docker.com/r/jenkins/jenkins