version: "3"

services:
  redis1:
    container_name: redis1
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    volumes:
      - /var/lib/redis1/data
    networks:
      - default
      - redis1-net
    environment:
      TZ: Asia/Seoul
