version: "3"

services:

  oracledb:
    container_name: oracle11gtest
    image: oracleinanutshell/oracle-xe-11g:latest
    restart: always
    ports:
      - 1523:1521
      - 5501:5500
    environment:
      - ORACLE_SID=devtestdb
      - ORACLE_PDB=devtestdb
      - ORACLE_PWD=devtestdbpass
      - ORACLE_USER=devtestuser
      - ORACLE_EDITION=EE
      - ORACLE_BASE=/opt/oracle
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_HOME=/opt/oracle/product/12.2.0.1/dbhome_1
    #      # oracle 이용시 기본 username = system password = oracle
    #      TZ: Asia/Seoul
    volumes:
      - ./oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
      - ./data-bridge:/data-bridge # just to have someplace to put data into the running container if needed

#    networks:
#      - default
#      - oracle-net