version: "3"

services:

  oracledb:
    container_name: oracle11g
    image: oracleinanutshell/oracle-xe-11g:latest
    restart: always
    ports:
      - 1522:1521
      - 5500:5500
    #    environment:
    #      ORACLE_PDB: dev
    #      ORACLE_SID: dev1
    #      ORACLE_PWD: dev!23
    #      ORACLE_USER: dev
    #      # oracle 이용시 기본 username = system password = oracle
    #      TZ: Asia/Seoul
    volumes:
      - C:\Users\dlthf\Documents\dockervol:/u01/app/oracle/db/oracle-xe-11g
#    networks:
#      - default
#      - oracle-net