#* @Name Env Create Properties
#* @Description 최초 환경설정시 사용 프로퍼티.
#* @Danger 테스트 금지입니다. DDL CREATE
#* @Author JangWonSeok
#* @CreateDate 2022. 11. 10.
Server:
  host: localhost
  port: 8010

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3309/UPLUS_CINNAMON
    username: root
    password: 1234
#    url: jdbc:log4jdbc:mysql://192.168.0.26/UPLUS_CINNAMON_2CH
#    username: icomsys
#    password: "#pass180901"
    owner: UPLUS_CINNAMON
    driver-class-name: net.sf.log4jdbc.DriverSpy
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    type: org.apache.tomcat.jdbc.pool.DataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: com.icomsys.main_vm.common.util.CustomDialect
#    generate-ddl: false
#https://docs.jboss.org/hibernate/orm/3.5/javadocs/org/hibernate/dialect/package-summary.html
  flyway:
    enabled: false
    baseline-on-migrate: false
feign:
  url:
    test: http://localhost:8014
    cinnamon: http://127.0.0.1:8080
    nlp: http://localhost:8014/ichatApi
    s3Bucket: local
    bgmpath: bgmfile/
    selvas: 172.31.34.52
    ttsport: 7890
    sttport: 9999

nlpapi: false

file:
  path: C:\workspace\multipartfile