version: "3"

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: user_me
      POSTGRES_PASSWORD: user_me
      TZ: Asia/Seoul
    volumes:
      - /var/lib/postgresql/data
#    networks:
#      - default
#      - postgresql-net