version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    #      - GITEA__database__DB_TYPE=mysql
    #      - GITEA__database__HOST=dev-ics-db.c9i6xgmcxx18.ap-northeast-2.rds.amazonaws.com
    #      - GITEA__database__NAME=gitea
    #      - GITEA__database__USER=ics_mgr
    #      - GITEA__database__PASSWD=#pass180901
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
      #    depends_on:
      #      - giteaMysql

      #  giteaMysql:
      #    image: mysql:8
      #    container_name: giteaMysql
      #    restart: always
      #    environment:
      #      - MYSQL_ROOT_PASSWORD=gitea
      #      - MYSQL_USER=gitea
      #      - MYSQL_PASSWORD=gitea
      #      - MYSQL_DATABASE=gitea
      #    ports:
      #      - 3310:3306
      #    networks:
      #      - gitea
      #    volumes:
      #      - ./mysql:/var/lib/mysql
      #  postgresql:
      #    container_name: postgresql
      #    image: postgres:latest
      #    restart: always
      #    ports:
      #      - 5432:5432
      #    environment:
      #      POSTGRES_DB: local
      #      POSTGRES_USER: user_me
      #      POSTGRES_PASSWORD: user_me
      #      TZ: Asia/Seoul
      #    volumes:
      #      - /var/lib/postgresql/data
      #    networks:
      #      - default
      #      - postgresql-net

      #  mariadb1:
      #    container_name: mariadb1
      #    image: mariadb
      #    restart: always
      #    ports:
      #      - 3307:3306
      #    environment:
      #      MARIADB_ROOT_PASSWORD: 1234
      #      MARIADB_DATABASE: ICS_DEV
      #      MARIADB_USER: dev
      #      MARIADB_PASSWORD: dev!23
      #      TZ: Asia/Seoul
      #    volumes:
      #      - /var/lib/postgresql/data
      #    networks:
      #      - default
      #      - mariadb-net

      #  oracledb:
      #    container_name: oracle11g
      #    image: oracleinanutshell/oracle-xe-11g:latest
      #    restart: always
      #    ports:
      #      - 1522:1521
      #      - 5500:5500
      #    environment:
      #      ORACLE_PDB: dev
      #      ORACLE_SID: dev1
      #      ORACLE_PWD: dev!23
      #      ORACLE_USER: dev
      #      # oracle 이용시 기본 username = system password = oracle
      #      TZ: Asia/Seoul
      #    volumes:
      #      - C:\Users\dlthf\Documents\dockervol:/u01/app/oracle/db/oracle-xe-11g
      #    networks:
      #      - default
      #      - oracle-net
      # connect
      # system oracle
      # create user ICS_DEV identified by pass180901;
      # grant connect, resource, dba to ICS_DEV;
      #  mysql:
      #    container_name: mysql
      #    image: mysql
      #    restart: always
      #    ports:
      #      - 3308:3306
      #    environment:
      #      MYSQL_ROOT_PASSWORD: 1234
      #      MYSQL_DATABASE: ICS_DEV
      #      MYSQL_USER: dev
      #      MYSQL_PASSWORD: dev!23
      #      TZ: Asia/Seoul
      #    volumes:
      #      - /var/lib/postgresql/data
      #    networks:
      #      - default
      #      - mysql-net

      #6379 포트는 그냥도커로 빌드해놈.

    #  redis1:
    #    container_name: redis1
    #    image: redis:latest
    #    restart: always
    #    ports:
    #      - 6380:6379
    #    volumes:
    #      - /var/lib/redis1/data
    #    networks:
    #      - default
    #      - redis1-net
    #    environment:
    #      TZ: Asia/Seoul

    #  jenkins:
    #    container_name: jenkinslocal
    #    image: jenkins/jenkins:jdk11
    #    restart: always
    #    ports:
    #      - 7999:8080
    #      - 50000:50000
    #    expose:
    #      - 8080
    #      - 50000
    #    volumes:
    #      - ./jenkins_home:/var/jenkins_home
    #      - ./home/wonseok/Documents/devWorkSpace/github/record/jenkins_home:/var/jenkins_home
    #      - /var/run/docker.sock:/var/run/docker.sock
    #      - C:\Program Files (x86)\jdk-11\lib\security\jenkins_home:/var/jenkins_home
    #    networks:
    #      - default
    #      - jenkins-net
    #    user: root
    #    environment:
    #      TZ: "Asia/Seoul"
    #    privileged: true
    #https://hub.docker.com/r/jenkins/jenkins


networks:
  postgresql-net:
  #    driver: bridge
  #  redis1-net:
  #    driver: bridge
  #  jenkins-net:
  #    driver: bridge
  #  mariadb-net:
  #    driver: bridge
  #  oracle-net:
  #    driver: bridge
  #  mysql-net:
  #    driver: bridge
  #  gitea:
  #    external: false
  gitea:
    driver: bridge


#volumes:
#  jenkinsvol: